### PR TITLE
feature: Remove Audit Log PVC

### PR DESCRIPTION
**Pull request by coreydaley**
https://issues.redhat.com/browse/RHIDP-4923

## Which issue(s) does this PR fix or relate to

- Fixes #_issue_number_

## PR acceptance criteria

- [x] Tests
- [x] Documentation
- [x] If the bundle manifests have been updated, make sure to review the [`rhdh-operator.clusterserviceversion.yaml`](../.rhdh/bundle/manifests/rhdh-operator.clusterserviceversion.yaml) file accordingly

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
@coreydaley Could you update your branch and fix the conflicts reported? Thanks.

image

**Comment by coreydaley** [comment]
@rm3l pull request has been rebased, ptal

**Review by gazarenkov — APPROVED** [review]

**Review by rm3l — APPROVED** [review]
/lgtm

**Pull request merged**
